#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${DEVCTL_ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
SERVER_DIR="$ROOT_DIR/ScopeSentry"
COMPOSE_FILE="$ROOT_DIR/scripts/dev-scan-docker-compose.yml"
LOCAL_DEV_DIR="${LOCAL_DEV_DIR:-$ROOT_DIR/.local-dev}"
RUNTIME_DIR="${SCAN_DOCKER_RUNTIME_DIR:-$LOCAL_DEV_DIR/runtime/scan-docker}"
ENV_FILE="$LOCAL_DEV_DIR/dev-scan-docker.env"

cd "$SERVER_DIR"

if [[ ! -f .env ]]; then
  echo "Missing $SERVER_DIR/.env"
  exit 1
fi

set -a
source ./.env
set +a

mkdir -p "$RUNTIME_DIR/config" "$RUNTIME_DIR/data" "$RUNTIME_DIR/plugin" "$RUNTIME_DIR/tmp"
mkdir -p "$LOCAL_DEV_DIR"

CONTAINER_NAME="${CONTAINER_NAME:-scopesentry-scan-dev}"
SCAN_IMAGE_VALUE="${SCAN_IMAGE:-autumn27/scopesentry-scan:latest}"
NODE_NAME="${NODE_NAME:-${NodeName:-local-dev-node-docker}}"
TIMEZONE_NAME="${TIMEZONE_NAME:-${TimeZoneName:-Asia/Shanghai}}"
MONGODB_IP_VALUE="${MONGODB_IP:-host.docker.internal}"
MONGODB_PORT_VALUE="${MONGODB_PORT:-27017}"
MONGODB_DATABASE_VALUE="${MONGODB_DATABASE:-ScopeSentry}"
MONGODB_USER_VALUE="${MONGODB_USER:-${MONGO_INITDB_ROOT_USERNAME:-admin}}"
MONGODB_PASSWORD_VALUE="${MONGODB_PASSWORD:-${MONGO_INITDB_ROOT_PASSWORD:-mongodb_password}}"
REDIS_IP_VALUE="${REDIS_IP:-host.docker.internal}"
REDIS_PORT_VALUE="${REDIS_PORT:-6379}"
REDIS_PASSWORD_VALUE="${REDIS_PASSWORD:-redis_password}"
TASK_MODE_VALUE="${TASK_MODE:-legacy}"
STREAM_PORTSCAN_ENABLED_VALUE="${STREAM_PORTSCAN_ENABLED:-false}"
ADAPTIVE_PULL_ENABLED_VALUE="${ADAPTIVE_PULL_ENABLED:-false}"
INTERACTSH_URL_VALUE="${INTERACTSH_URL:-}"
INTERACTSH_TOKEN_VALUE="${INTERACTSH_TOKEN:-}"
NUCLEI_DEBUG_VALUE="${NUCLEI_DEBUG:-}"
NUCLEI_STATS_VALUE="${NUCLEI_STATS:-}"
NUCLEI_STATS_INTERVAL_VALUE="${NUCLEI_STATS_INTERVAL:-}"
NUCLEI_DEBUG_REQUEST_VALUE="${NUCLEI_DEBUG_REQUEST:-}"
NUCLEI_DEBUG_RESPONSE_VALUE="${NUCLEI_DEBUG_RESPONSE:-}"
NUCLEI_TASK_ENGINE_TRACE_VALUE="${NUCLEI_TASK_ENGINE_TRACE:-}"

cat >"$ENV_FILE" <<EOF
CONTAINER_NAME=$CONTAINER_NAME
SCAN_IMAGE=$SCAN_IMAGE_VALUE
NODE_NAME=$NODE_NAME
TIMEZONE_NAME=$TIMEZONE_NAME
MONGODB_IP=$MONGODB_IP_VALUE
MONGODB_PORT=$MONGODB_PORT_VALUE
MONGODB_DATABASE=$MONGODB_DATABASE_VALUE
MONGODB_USER=$MONGODB_USER_VALUE
MONGODB_PASSWORD=$MONGODB_PASSWORD_VALUE
REDIS_IP=$REDIS_IP_VALUE
REDIS_PORT=$REDIS_PORT_VALUE
REDIS_PASSWORD=$REDIS_PASSWORD_VALUE
TASK_MODE=$TASK_MODE_VALUE
STREAM_PORTSCAN_ENABLED=$STREAM_PORTSCAN_ENABLED_VALUE
ADAPTIVE_PULL_ENABLED=$ADAPTIVE_PULL_ENABLED_VALUE
INTERACTSH_URL=$INTERACTSH_URL_VALUE
INTERACTSH_TOKEN=$INTERACTSH_TOKEN_VALUE
NUCLEI_DEBUG=$NUCLEI_DEBUG_VALUE
NUCLEI_STATS=$NUCLEI_STATS_VALUE
NUCLEI_STATS_INTERVAL=$NUCLEI_STATS_INTERVAL_VALUE
NUCLEI_DEBUG_REQUEST=$NUCLEI_DEBUG_REQUEST_VALUE
NUCLEI_DEBUG_RESPONSE=$NUCLEI_DEBUG_RESPONSE_VALUE
NUCLEI_TASK_ENGINE_TRACE=$NUCLEI_TASK_ENGINE_TRACE_VALUE
RUNTIME_DIR=$RUNTIME_DIR
EOF

if [[ $# -eq 0 ]]; then
  set -- up -d
elif [[ $# -eq 1 && "$1" == "up" ]]; then
  set -- up -d
fi

if [[ "$1" == "up" ]]; then
  "$ROOT_DIR/scripts/dev-db-up.sh" >/dev/null
fi

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"

if [[ "$1" == "up" || "$1" == "ps" ]]; then
  printf 'container_name=%s\n' "$CONTAINER_NAME"
  printf 'scan_image=%s\n' "$SCAN_IMAGE_VALUE"
  printf 'node_name=%s\n' "$NODE_NAME"
  printf 'runtime_dir=%s\n' "$RUNTIME_DIR"
  printf 'compose_file=%s\n' "$COMPOSE_FILE"
  printf 'logs_cmd=%s\n' "docker logs -f $CONTAINER_NAME"
fi
